#!/usr/bin/env python3
# This file is placed in the Public Domain.


"cleanup"


## import


import os


## define


cwd = os.getcwd()

SKIPDIR = [".git", ".pytest_cache", "env"]


## utility


def popen(txt, silent=False):
    "run command"
    for line in os.popen(txt).readlines():
        if silent:
            continue
        print(line.strip())


def loop(path, txt, silent=False):
    "walk directories"
    for fnn in os.listdir(path):
        if fnn in SKIPDIR or fnn.startswith("."):
            continue
        if not os.path.isdir(fnn):
            continue
        os.chdir(fnn)
        popen(txt, silent)
        os.chdir("..")


## runtime


def main():
    "main"
    popen("rm -fRv build dist MANIFEST *.egg-info")
    loop(cwd, "rm -fRv *~")
    loop(cwd, "rm -fRv __pycache__", True)


if __name__ == "__main__":
    main()
